### ISSUE TITLE
urlparse issue

### ISSUE THREAD

**Issue by AtumGame** [Gandum2077/PyEhViewer#2]
大佬您好，多谢分享艺（工）术（口）阅读器。我在下载时不管保存在哪个文档都会显示no module named urlparse。这是什么原因导致的呢。
![F3E028D0-CCBC-465E-A46A-CCC8AB5C6DBA](https://user-images.githubusercontent.com/59200208/71426983-800f6100-2706-11ea-8de9-7344ce3138c6.png)

**Comment by Gandum2077** [comment]
仔细看文档

> stash必须要运行在Python 2.7环境下。
